### PR TITLE
DEQM IG Ballot Comments applied March 2023

### PR DESCRIPTION
**Pull request by mholck**
FHIR-39979
FHIR-40112
FHIR-40132
FHIR-40133

### CODE REVIEW

**Review by yanheras — CHANGES_REQUESTED** [review]
"The collection of resources consisting of the DEQM Summary MeasureReport Profile and the relevant QI Core and DEQM profiles representing the detailed patient data to support calculations of those CQMs is similar to the QRDA Category III in the QDM-CQL-QRDA paradigm." This sentence from the Individual Reporting page does not fit Summary Reporting. 

Here is the paragraph with the suggested wording changes:
As described in the Quality Measurement Standards Landscape section of this implementation guide, the QI Core IG defines a set of FHIR profiles with extensions and bindings needed to create interoperable, quality-focused applications. For implementers that are familiar with the previous generation of standards that supports summary reporting---Quality Data Model (QDM), Clinical Quality Language (CQL), and the Quality Reporting Document Architecture Category III (QRDA Category III), QI Core profiles are equivalent to the Quality Data Model (QDM) and the DEQM Summary MeasureReport Profile is equivalent to the QRDA Category III in the QDM-CQL-QRDA paradigm.

**Review by yanheras — CHANGES_REQUESTED** [review]
Re: FHIR-40112
"A reporter.group" should be added to the 2nd block of the bulleted items instead under the heading "Each {{site.data.structuredefinitions.[id].type}} *should* have ([Must Support]):", because report.groupp is 0..1

**Review by yanheras — COMMENTED** [review]
Looks good

**Review by yanheras — COMMENTED** [review]
Looks good

**Comment by mholck** [comment]
All suggested changes have been made but if you want to hold on the PR until 40112 is resolved that is fine

**Pull request merged**
