### PR TITLE
TACOSTRAT-918 - Update GuidanceResponse Profile for Vote

### PR DESCRIPTION
**Pull request by awatson1978**
https://jira.mitre.org/browse/TACOSTRAT-918
https://jira.hl7.org/browse/FHIR-35807

### CODE REVIEW

**Comment by awatson1978** [comment]
Review available at:
https://build.fhir.org/ig/HL7/davinci-deqm/branches/TACOSTRAT-918/StructureDefinition-detailedCareGapGuidanceResponse.html

**Comment by awatson1978** [comment]
Profiles here:
[file:///Users/awatson/Code/implementation-guides/davinci-deqm/output/profiles.html](https://build.fhir.org/ig/HL7/davinci-deqm/branches/TACOSTRAT-918/profiles.html)

**Comment by brynrhodes** [comment]
Removed FSH, we're not ready for that in this IG, if we do switch to FSH it should be all at once. Also updated conventions and removed duplicate codesystem/valueset resources.

**Comment by brynrhodes** [comment]
I'm going to merge this, but there is still work to be done on the ticket, we're missing explanatory text about when/how to use the profile, as well as examples.

**Pull request merged**
